### PR TITLE
Added Polish translation

### PR DESCRIPTION
**Pull request by romali**
I noticed that switching between languages freezes arizen. login page, backup/import need to be translated as well.

### CODE REVIEW

**Comment by LukasBures** [comment]
Thank you for your work, we are still working on the translation texts, we will inform all when it will be done and ready for making translations.

**Comment by romali** [comment]
On Debian, after switching language, content of arizen become white and console is showing following message:
`[17614:1229/145307.395029:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
#0 0x0000036228e7 <unknown>
#1 0x00000363862b <unknown>
#2 0x0000035e4595 <unknown>
#3 0x0000034f29fd <unknown>
#4 0x7f149abe8c23 <unknown>
#5 0x7f149af593c2 <unknown>
#6 0x7f149af64d61 <unknown>
#7 0x7f149af5a20e <unknown>
#8 0x7f149af52b67 <unknown>
#9 0x7f149af50569 <unknown>
#10 0x7f149adf44c3 <unknown>
#11 0x7f149adf2d5a <unknown>
#12 0x7f149adf22d4 <unknown>
#13 0x7f149ae00936 <unknown>
#14 0x7f149ab98813 <unknown>
#15 0x0000036163a0 <unknown>
#16 0x000003472028 <unknown>
#17 0x0000034702c8 <unknown>
#18 0x0000036163a0 <unknown>
#19 0x00000363c48d <unknown>
#20 0x00000363c7a8 <unknown>
#21 0x00000363ce46 <unknown>
#22 0x00000361b1da <unknown>
#23 0x00000363c1b7 <unknown>
#24 0x0000035eec6e <unknown>
#25 0x0000014f2a40 <unknown>
#26 0x0000013c0a6a <unknown>
#27 0x0000013c1908 <unknown>
#28 0x000001097d3f <unknown>
#29 0x0000013c1c42 <unknown>
#30 0x000003de1228 main
#31 0x7f149376e2b1 __libc_start_main
#32 0x0000005a5c59 <unknown>
`

**Comment by LukasBures** [comment]
It should be fixed in #176

**Comment by LukasBures** [comment]
please translate it once again with all key-entry, see #173, thank you.

**Pull request closed without merging**
