### PR TITLE
Balance Equivalent in Fiat - Feature

### PR DESCRIPTION
**Pull request by gsfakianakis**
Added in bottom bar the equivalent of all wallets in USD.

- [x] Api is ready for other fiat currencies:
"AUD", "BRL", "CAD", "CHF", "CLP", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF", "IDR", "ILS", "INR", "JPY", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PKR", "PLN", "RUB", "SEK", "SGD", "THB", "TRY", "TWD", "ZAR"

Things to do:
 - [x] Specify in Settings the desired fiat to display (USD as default).
 - [x] Display of time in different format (?)
 - [x] Refresh every X minutes
 - [ ] Make nicer drop down list @neduchal

### CODE REVIEW

**Comment by LukasBures** [comment]
- The first "/" is green, it should be color like others - gray
- I think "USD/ZEN" could be omited.
- and the string should be "Last update:" instead of "Last Updated:" 
- and the time format is really long, the time e.g. 11:04:24 should be enought 

snimek obrazovky 2017-12-22 v 11 05 56

**Comment by LukasBures** [comment]
Add dropdown list to the Settings menu - like you have it in your TODO list.

**Comment by gsfakianakis** [comment]
Full list of fiat currencies will be added.

Possible error: New account has not any preferred fiat currency. In this case USD is set as default. I checked once and it works. Probably should be checked by one of you.

**Comment by LukasBures** [comment]
When I started Arizen, there wasn't any currency selected:

snimek obrazovky 2017-12-25 v 19 16 37

**Comment by LukasBures** [comment]
Then I went to the settings and selected the CZK, then when i reopen Arizen CZK was already selected. 

Great work!

snimek obrazovky 2017-12-25 v 19 16 53

**Comment by LukasBures** [comment]
Just small improvement: it would be nice if there will be any space separator between every 3 digits:

not: 1000000.00
but: 1 000 000.00

or something like that, when a user can simply count digits.

**Comment by LukasBures** [comment]
Refresh functionality would be handy, e.g. refresh every 5 mins

**Comment by LukasBures** [comment]
@neduchal please take a look at drop-down menu "Fiat Equivalent" appearance, please tune CSS for better visual integration.

**Comment by gsfakianakis** [comment]
For "Refresh every X minutes":
When refresh button is pressed there is a sequence of functions called:

refresh() --> ipcRenderer.send("refresh-wallet"); --> updateBlockchainView() --> webContents.send('update-wallet-balance',...); -->  setTotalBalance(msg.total); --> setBalanceText(totalBalanceNode, balance) and  setFiatBalanceText(balanceZEN);

So refresh of fiat comes after the refresh of total balance. No need to implement anything different.

**Comment by woky** [comment]
Yeah. Automatic refresh is done every 5 minutes. If you're hooked on `update-wallet-balance` message, there's no need to change anything.

**Comment by LukasBures** [comment]
Nice, thank you.

**Comment by LukasBures** [comment]
merged

**Pull request merged**
