### PR TITLE
Paper Wallet Generator - Feature

### PR DESCRIPTION
**Pull request by gsfakianakis**
Paper Wallet Generator

### Things Added:
- [x] Button generate new paper wallet  
- [x]  Checkbox "add this wallet to Arizen?" 
- [x]  Export PDF file with all QR codes and hashes under that QRs 

### Things to improve:
- [x] Print Area
- [x] New paper wallet added in Arizen does not appear unless I restart the app
- [x] Fix file path and file extension

### Issues:
- [ ]  Do not show QR codes if user generated 3-4 wallets without reloading app. When I close the dialog using the X button, everything is fine. If I use the escape button in the keyboard, the next wallet generation fails to load qr codes.

### CODE REVIEW

**Comment by LukasBures** [comment]
@woky please check refresh when new wallet is added, see: "New paper wallet added in Arizen does not appear unless I restart the app"

**Comment by LukasBures** [comment]
Great work! I really appreciate it!

**Comment by LukasBures** [comment]
Testing OS MacOS:

I would love to have _name_, _checkbox_ and _button_ in one centered column instead of in one row

snimek obrazovky 2017-12-22 v 10 44 19

**Comment by LukasBures** [comment]
Testing OS:

When I want to export wallet the file extension is there multiple times - see image:

snimek obrazovky 2017-12-22 v 10 44 55

**Comment by LukasBures** [comment]
Testing OS: MacOS

When I export QRs to the pdf file, the addresses are cutted off the paper size (this could be maybe my issue).

I would like to see the Zencash name and Zencash logo in that pdf file somewhere.

snimek obrazovky 2017-12-22 v 10 45 35

**Comment by LukasBures** [comment]
When I click "add a paper wallet to Arizen" checkbox button then the wallet isn't there, wallet list should be refreshed. (after reopening Arizen the previously created paper wallet is there).

**Comment by gsfakianakis** [comment]
@LukasBures please check the double .pdf issue in macOS.

The "address list should be refreshed" not yet fixed: next step.

**Comment by LukasBures** [comment]
Please:
- center name, checkbox and button
- remove logo

snimek obrazovky 2017-12-25 v 19 03 47

**Comment by LukasBures** [comment]
When I click on logo, I am redirected to our website, but it is opened in Arizen and I have no chance to return back.

Remove that link or let open that URL in web browser.

snimek obrazovky 2017-12-25 v 19 03 56

**Comment by LukasBures** [comment]
In default window size the hashes are still "behind the edge"

snimek obrazovky 2017-12-25 v 19 05 59

same in PDF (link under logo works in PDF - that is awesome)

snimek obrazovky 2017-12-25 v 19 07 24

**Comment by LukasBures** [comment]
The path is almost solved - see the image:

Please use default name "ZenCash Wallet" (instead of "ZenCashWallet") only if user doesnt enter his/her own name, then use users name.

snimek obrazovky 2017-12-25 v 19 06 30

**Comment by gsfakianakis** [comment]
@LukasBures Please make this more clear:
"Please use default name "ZenCash Wallet" (instead of "ZenCashWallet") only if user doesnt enter his/her own name, then use users name."

I understand this:
    if (!(newWalletNamePaper==="")){
      var defaultPathPDF = "*/"+newWalletNamePaper+" Wallet - " + userInfo.login;
    } else {
      var defaultPathPDF = "*/ZenCash Wallet - " + userInfo.login;
    }

**Comment by LukasBures** [comment]
"Please use default name "ZenCash Wallet" (instead of "ZenCashWallet") only if user does not enter his/her own name, then use users name."

Now it is great, thank you.

**Comment by gsfakianakis** [comment]
@LukasBures Do not merge until I clean the code. Let me know when everything is ok from your side.

**Comment by gsfakianakis** [comment]
About: " Do not show QR codes if user generated 3-4 wallets without reloading app."
When I close the dialog using the X button, everyting is fine. If I use the escape button in the keyboard, the next wallet generation fails to load qr codes.

**Pull request merged**
