### PR TITLE
Balance Equivalent in Fiat - Feature - Improve  and fix issues

### PR DESCRIPTION
**Pull request by gsfakianakis**
### Issues to fix
1. - [x]  [10538:1227/200919.127767:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
    - [x] Test in in Linux/Debian 9
    - [x] Test in Windows (7)
    - [x] Test in MacOS

2. - [x] Refresh together with balance
### Improvments
- [x] Clean Code

### CODE REVIEW

**Comment by gsfakianakis** [comment]
About issue 1:

window is getting all white with error:
[10538:1227/200919.127767:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
#0 0x0000036228e7 <unknown>
#1 0x00000363862b <unknown>
#2 0x0000035e4595 <unknown>
#3 0x0000034f29fd <unknown>
#4 0x7f561cd8dc23 <unknown>
#5 0x7f561d0fe3c2 <unknown>
#6 0x7f561d109d61 <unknown>
#7 0x0000036210b3 <unknown>
#8 0x000003628393 <unknown>
#9 0x7f561c453494 start_thread
#10 0x7f56159daaff clone

**Comment by gsfakianakis** [comment]
@LukasBures Please test macOS.

@all Please take a look and let me know if anything should be fixed/cleared.

Then I will do the last commits and the PR could be merged.

**Comment by LukasBures** [comment]
It works great!

Just one small thing, when I save setting (and I change Fiat currency) then I have to wait until next update is called (that can be the 5minutes maximum). And in that time, I have "NaN" value in Fiat balance.

snimek obrazovky 2017-12-28 v 23 16 25

It would be preferable to call update Fiat function when user click "Save" button - but only if the selected Fiat currency was changed.

snimek obrazovky 2017-12-28 v 23 23 50

**Comment by gsfakianakis** [comment]
Can you paste here any log output ? 

When user selects fiat, then the update function is called. 

If you have another OS available could you test also there ?

**Comment by LukasBures** [comment]
I don't have any other OS.

In log there is nothing.

**Comment by LukasBures** [comment]
The "NaN" problem is now fixed.

**Comment by LukasBures** [comment]
@gsfakianakis please:

1) Instead of `const axios = require("axios");` use `const request = require("request");` if that is possible for get and post requests. You can inspire yourself in `main.js` in function: `ipcMain.on("send", function (event, fromAddress, toAddress, fee, amount)` 
2) clear the code

**Comment by gsfakianakis** [comment]
- Code cleaned.
- request package give the same error (issue 1 above), axios will be used until we further take a look into this.

**Pull request merged**
